AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda function with its permission
Resources:
  DataCenterLambdaFunction:
    Type: AWS::Lambda::Function 
    Properties:
      FunctionName: datacenter-lambda
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            print("Welcome to KKE AWS Labs!")
            return {"statusCode": 200, "body": "Welcome to KKE AWS Labs!"}
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda_execution_role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole