# This script is generated by chatGPT
# The goal here is to learn how to implement a clean script
# and have a reference whenever I need it

#!/bin/bash

# Variables
REGION="us-east-1"
DB_INSTANCE_ID="nautilus-rds"
DB_NAME="nautilusdb"
DB_USER="admin"
DB_PASSWORD="Admin12345!"
DB_SUBNET_GROUP="nautilus-private-subnet-group"
SECURITY_GROUP_NAME="nautilus-rds-sg"

echo "Creating Security Group for RDS..."

# Get default VPC
VPC_ID=$(aws ec2 describe-vpcs \
  --region $REGION \
  --query "Vpcs[0].VpcId" \
  --output text)

# Create security group
SG_ID=$(aws ec2 create-security-group \
  --group-name $SECURITY_GROUP_NAME \
  --description "Security group for private RDS" \
  --vpc-id $VPC_ID \
  --region $REGION \
  --query 'GroupId' \
  --output text)

echo "Security Group Created: $SG_ID"

# Allow MySQL access within VPC only
aws ec2 authorize-security-group-ingress \
  --group-id $SG_ID \
  --protocol tcp \
  --port 3306 \
  --cidr 10.0.0.0/16 \
  --region $REGION

echo "Creating DB Subnet Group..."

# Get private subnets (modify filter if needed)
PRIVATE_SUBNETS=$(aws ec2 describe-subnets \
  --region $REGION \
  --query "Subnets[?MapPublicIpOnLaunch==\`false\`].SubnetId" \
  --output text)

aws rds create-db-subnet-group \
  --db-subnet-group-name $DB_SUBNET_GROUP \
  --db-subnet-group-description "Private subnet group for RDS" \
  --subnet-ids $PRIVATE_SUBNETS \
  --region $REGION

echo "Creating Private MySQL RDS Instance..."

aws rds create-db-instance \
  --region $REGION \
  --db-instance-identifier $DB_INSTANCE_ID \
  --db-instance-class db.t3.micro \
  --engine mysql \
  --engine-version 8.4.0 \
  --allocated-storage 20 \
  --max-allocated-storage 50 \
  --master-username $DB_USER \
  --master-user-password $DB_PASSWORD \
  --db-name $DB_NAME \
  --vpc-security-group-ids $SG_ID \
  --db-subnet-group-name $DB_SUBNET_GROUP \
  --no-publicly-accessible \
  --storage-type gp2 \
  --backup-retention-period 7

echo "Waiting for RDS instance to become available..."

aws rds wait db-instance-available \
  --db-instance-identifier $DB_INSTANCE_ID \
  --region $REGION

echo "RDS Instance is now AVAILABLE ✅"

# Show endpoint
aws rds describe-db-instances \
  --db-instance-identifier $DB_INSTANCE_ID \
  --region $REGION \
  --query "DBInstances[0].Endpoint.Address" \
  --output text