# k create ns 
apiVersion: v1
kind: Service
metadata:
  name: node-service-xfusion 
spec:
  type: NodePort
  selector:
    app: node
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30012
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: node-deployment-xfusion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node 
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container-xfusion
        image: gcr.io/kodekloud/centos-ssh-enabled:node
        ports: 
        - containerPort: 8080
