apiVersion: v1
kind: Secret 
metadata:
  name: media
data:
  media.txt: NWVjdXIz

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec: 
  volumes:
  - name: secret-media
    secret:
      secretName: media
  containers:
  - name: secret-container-xfusion
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
    - name: secret-media 
      readOnly: true
      mountPath: /opt/games